### ISSUE TITLE
BookSystem Roadmap

### ISSUE THREAD

**Issue by Sparkypen7** [Sparkypen7/BookSystem#1]
This is the Roadmap for the Roblox BookSystem.

It consists of what is expected to come, and what has delivered over time. 

# Alpha Phase

When all of the following check boxes have been checked, that declares that BookSystem would be readily available and steady enough for production roll-outs. 

## Creating Books
- [ ] Entirely in-game
- [ ] Text filtering and preview
- [ ] Optional Librarian review
- [ ] Markdown support for formatting the book
- [ ] Books can be removed by a publisher and / or the Author

## Publishing Books
- [ ] Optional system where Authors are required to have books published by a publisher
- [ ] Publishers can suggest changes and deny books.
- [ ] Publishers can remove books from a library, if the library allows it.
- [ ] Authors accepting a publisher offer will be prompted on the permissions that publishers have
- [ ] Publishers are global and not game-specific.
- [ ] Publishers and Editors can be synced with 

## Librarians
- [ ] Optional System for reviewing books similar to Publishers
- [ ] Can manually catalog books
- [ ] Can mark books under review and take them down temporarily if it violates a library's rules or Roblox's Terms of Usage / Community Rules
## Book Data
- [ ] Server-sided positional syncing
- [ ] Custom layout orders (similar to UILayout instances) that dynamically position books based off of their shelve positions
- [ ] Writing books in-game and publishing
- [ ] Live preview of Roblox's filter system.
- [ ] A manual webhook can be sent to external websites such as Discord, so you can view books on other platforms other than Roblox
